name: CI / Build & Static Analysis

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore
      # Continue on error to avoid failing if there are warnings treated as errorsdcscssd
      - run: |
          cp .editorconfig.base .editorconfig
          dotnet build -c Release | tee build-base.log || true
          dotnet test -c Release | tee test-base.log || true

      - uses: actions/upload-artifact@v4
        with:
          name: base-logs
          path: |
            build-base.log
            test-base.log

      - run: |
          cp .editorconfig.strict .editorconfig
          dotnet build -c Release | tee build-strict.log || true
          dotnet test -c Release | tee test-strict.log || true

      - uses: actions/upload-artifact@v4
        with:
          name: strict-logs
          path: |
            build-strict.log
            test-strict.log
